spring:
  security:
    user:
      name: config
      password: config
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Development/repo/config-repo
          search-paths: '{application}'